import { adminApi as baseAdminApi, previewDocumento } from "../../../features/admin/api/adminApi";

export const adminApi = {
    getAdminDashboard: baseAdminApi.getAdminDashboard,

    getSolicitudesVerificacion: baseAdminApi.getSolicitudesVerificacion,
    getSolicitudVerificacionDetalle: baseAdminApi.getSolicitudVerificacionDetalle,
    aprobarSolicitudVerificacion: baseAdminApi.aprobarSolicitud,
    rechazarSolicitudVerificacion: baseAdminApi.rechazarSolicitud,
    solicitarSubsanacionSolicitud: baseAdminApi.solicitarSubsanacion,
    aprobarFaseSolicitudVerificacion: baseAdminApi.aprobarFaseSolicitud,
    rechazarFaseSolicitudVerificacion: baseAdminApi.rechazarFaseSolicitud,
    previewDocumentoVerificacion: previewDocumento,

    getAdminUsuarios: baseAdminApi.getAdminUsuarios,
    getAdminUsuarioDetalle: baseAdminApi.getAdminUsuarioDetalle,
    activarAdminUsuario: baseAdminApi.activarUsuario,
    desactivarAdminUsuario: baseAdminApi.desactivarUsuario,
    cambiarRolAdminUsuario: baseAdminApi.cambiarRolUsuario,

    getAdminEmpresas: baseAdminApi.getAdminEmpresas,
    getAdminEmpresaDetalle: baseAdminApi.getAdminEmpresaDetalle,
    activarAdminEmpresa: baseAdminApi.activarEmpresa,
    desactivarAdminEmpresa: baseAdminApi.desactivarEmpresa,
    getAdminEmpresaModulos: baseAdminApi.getEmpresaModulos,
    activarModuloEmpresa: baseAdminApi.activarModuloEmpresa,
    desactivarModuloEmpresa: baseAdminApi.desactivarModuloEmpresa,

    getAdminAuditoria: baseAdminApi.getAdminAuditoria,

    getAdminCatalogos: baseAdminApi.getAdminCatalogos,
    getAdminModulos: baseAdminApi.getAdminModulos,
    getAdminRoles: baseAdminApi.getAdminRoles,
    crearAdminModulo: baseAdminApi.crearModulo,
    actualizarAdminModulo: baseAdminApi.actualizarModulo,
    activarAdminModulo: baseAdminApi.activarModulo,
    desactivarAdminModulo: baseAdminApi.desactivarModulo,
    getTiposCliente: baseAdminApi.getTiposCliente,
    crearTipoCliente: baseAdminApi.crearTipoCliente,
    actualizarTipoCliente: baseAdminApi.actualizarTipoCliente,
    activarTipoCliente: baseAdminApi.activarTipoCliente,
    desactivarTipoCliente: baseAdminApi.desactivarTipoCliente,
    getTiposLocalizacionCliente: baseAdminApi.getTiposLocalizacionCliente,
    crearTipoLocalizacionCliente: baseAdminApi.crearTipoLocalizacionCliente,
    actualizarTipoLocalizacionCliente: baseAdminApi.actualizarTipoLocalizacionCliente,
    activarTipoLocalizacionCliente: baseAdminApi.activarTipoLocalizacionCliente,
    desactivarTipoLocalizacionCliente: baseAdminApi.desactivarTipoLocalizacionCliente,
    getTiposEmpresa: baseAdminApi.getTiposEmpresa,
    getTiposDocumentoIdentidad: baseAdminApi.getTiposDocumentoIdentidad,
};

export const {
    getAdminDashboard,
    getSolicitudesVerificacion,
    getSolicitudVerificacionDetalle,
    aprobarSolicitudVerificacion,
    rechazarSolicitudVerificacion,
    solicitarSubsanacionSolicitud,
    aprobarFaseSolicitudVerificacion,
    rechazarFaseSolicitudVerificacion,
    previewDocumentoVerificacion,
    getAdminUsuarios,
    getAdminUsuarioDetalle,
    activarAdminUsuario,
    desactivarAdminUsuario,
    cambiarRolAdminUsuario,
    getAdminEmpresas,
    getAdminEmpresaDetalle,
    activarAdminEmpresa,
    desactivarAdminEmpresa,
    getAdminEmpresaModulos,
    activarModuloEmpresa,
    desactivarModuloEmpresa,
    getAdminAuditoria,
    getAdminCatalogos,
    getAdminModulos,
    getAdminRoles,
    crearAdminModulo,
    actualizarAdminModulo,
    activarAdminModulo,
    desactivarAdminModulo,
    getTiposCliente,
    crearTipoCliente,
    actualizarTipoCliente,
    activarTipoCliente,
    desactivarTipoCliente,
    getTiposLocalizacionCliente,
    crearTipoLocalizacionCliente,
    actualizarTipoLocalizacionCliente,
    activarTipoLocalizacionCliente,
    desactivarTipoLocalizacionCliente,
    getTiposEmpresa,
    getTiposDocumentoIdentidad,
} = adminApi;
