export const endpoints = {
    auth: {
        login: "auth/login",
        logout: "auth/logout",
        me: "auth/me",
        register: "auth/register",
    },
    catalogos: {
        tiposCliente: "tipos-cliente",
        tiposDocumentoIdentidad: "tipos-documento-identidad",
        tiposEmpresa: "tipos-empresa",
    },
    clientes: "clientes",
    servicios: "servicios",
    tiposTarifaServicio: "tipos-tarifa-servicio",
    adminTiposTarifaServicio: "admin/tipos-tarifa-servicio",
    servicioPrecios: "servicio-precios",
    ordenesTrabajo: "ordenes-trabajo",
    calendarioEventos: "calendario-eventos",
    dashboardCalendario: "dashboard/calendario",
    proximasOrdenes: "dashboard/proximas-ordenes",
    dashboard: {
        resumen: "dashboard/resumen",
        calendario: "dashboard/calendario",
        proximasOrdenes: "dashboard/proximas-ordenes",
    },
    facturas: "facturas",
    registrosFacturacion: "registros-facturacion",
    verifactu: "verifactu",
    inventario: {
        items: "inventario-items",
        ubicaciones: "inventario-ubicaciones",
        unidadesMedida: "inventario-unidades-medida",
        movimientos: "inventario-movimientos",
        tiposMovimiento: "tipos-inventario-movimiento",
    },
    calendario: "calendario-eventos",
    informes: "informes",
    empresa: "empresa",
    admin: "admin",
};
