export const endpoints = {
    auth: {
        login: "auth/login",
        logout: "auth/logout",
        me: "auth/me",
        register: "auth/register",
    },
    catalogos: {
        tiposCliente: "tipos-cliente",
        tiposDocumentoIdentidad: "tipos-documento-identidad",
        tiposEmpresa: "tipos-empresa",
    },
    clientes: "empresa/clientes",
    servicios: "empresa/servicios",
    tiposTarifaServicio: "tipos-tarifa-servicio",
    adminTiposTarifaServicio: "admin/tipos-tarifa-servicio",
    servicioPrecios: "empresa/servicio-precios",
    ordenesTrabajo: "empresa/ordenes-trabajo",
    calendarioEventos: "empresa/calendario-eventos",
    dashboardCalendario: "empresa/dashboard/calendario",
    proximasOrdenes: "empresa/dashboard/proximas-ordenes",
    dashboard: {
        resumen: "empresa/dashboard/resumen",
        calendario: "empresa/dashboard/calendario",
        proximasOrdenes: "empresa/dashboard/proximas-ordenes",
    },
    facturas: "empresa/facturas",
    registrosFacturacion: "empresa/registros-facturacion",
    verifactu: "empresa/verifactu",
    inventario: {
        items: "empresa/inventario-items",
        ubicaciones: "empresa/inventario-ubicaciones",
        unidadesMedida: "inventario-unidades-medida",
        movimientos: "empresa/inventario-movimientos",
        tiposMovimiento: "tipos-inventario-movimiento",
    },
    calendario: "empresa/calendario-eventos",
    empresa: "empresa",
    admin: "admin",
};
