import {
    Boxes,
    BriefcaseBusiness,
    Building2,
    CalendarDays,
    ChevronLeft,
    ChevronRight,
    ClipboardList,
    Download,
    Eye,
    FileText,
    FileSearch,
    LayoutDashboard,
    LogIn,
    Pencil,
    Plus,
    Search,
    Settings,
    ShieldCheck,
    SlidersHorizontal,
    UsersRound,
    Trash2,
    UserCog,
    UserPlus,
    Users,
} from "lucide-react";

export const appIcons = {
    dashboard: LayoutDashboard,
    clientes: Users,
    empresa: Building2,
    servicios: BriefcaseBusiness,
    ordenes: ClipboardList,
    calendario: CalendarDays,
    anterior: ChevronLeft,
    facturas: FileText,
    inventario: Boxes,
    configuracion: Settings,
    admin: UserCog,
    auditoria: FileSearch,
    filtros: SlidersHorizontal,
    usuarios: UsersRound,
    login: LogIn,
    registro: UserPlus,
    validar: ShieldCheck,
    ver: Eye,
    editar: Pencil,
    eliminar: Trash2,
    buscar: Search,
    crear: Plus,
    siguiente: ChevronRight,
    descargar: Download,
};
